BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Assembly] (
    [assemblyId] INT NOT NULL IDENTITY(1,1),
    [name] NVARCHAR(1000) NOT NULL,
    [jsonData] NVARCHAR(max) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Assembly_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [Assembly_pkey] PRIMARY KEY CLUSTERED ([assemblyId]),
    CONSTRAINT [Assembly_name_key] UNIQUE NONCLUSTERED ([name])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
